In [1]:
import torch

In [4]:
import numpy as np
import matplotlib.pyplot as plt
 
def getPositionEncoding(seq_len, d, n=10000):
    P = np.zeros((seq_len, d))
    for k in range(seq_len):
        for i in np.arange(int(d/2)):
            denominator = np.power(n, 2*i/d)
            P[k, 2*i] = np.sin(k/denominator)
            P[k, 2*i+1] = np.cos(k/denominator)
    return P
 
P = getPositionEncoding(seq_len=4, d=5, n=100)
print(P)

[[ 0.          1.          0.          1.          0.        ]
 [ 0.84147098  0.54030231  0.15782664  0.98746684  0.        ]
 [ 0.90929743 -0.41614684  0.31169715  0.9501815   0.        ]
 [ 0.14112001 -0.9899925   0.45775455  0.88907861  0.        ]]


In [3]:

P = getPositionEncoding(seq_len=4, d=4, n=100)
print(P)

[[ 0.          1.          0.          1.        ]
 [ 0.84147098  0.54030231  0.09983342  0.99500417]
 [ 0.90929743 -0.41614684  0.19866933  0.98006658]
 [ 0.14112001 -0.9899925   0.29552021  0.95533649]]
